services:
  web:
    build:
      context: .
      args:
        SITE_URL: ${SITE_URL}
        BASE_PATH: ${BASE_PATH:-/}
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
